sudo: required

services:
  - docker

before_install:
  - docker build -t endo9e7a6/docker-react-demo -f Dockerfile.dev .

script:
  - docker run endo9e7a6/docker-react-demo npm run test -- --coverage
